//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zakupka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int CatalogId { get; set; }
        public int Count { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
